version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web_v1
      - web_v2
      - web_v3

  web_v1:
    image: nginx
    ports:
      - "81:80"
    volumes:
      - ./web1/nginx.conf:/etc/nginx/nginx.conf

  web_v2:
    image: nginx
    ports:
      - "82:80"
    volumes:
      - ./web2/nginx.conf:/etc/nginx/nginx.conf

  web_v3:
    image: nginx
    ports:
      - "83:80"
    volumes:
      - ./web3/nginx.conf:/etc/nginx/nginx.conf
